### ISSUE TITLE
accelerator.prepare() CUDA out of memory

### ISSUE THREAD

**Issue by zouce** [princeton-nlp/SimPO#10]
Hi, I run the code with `ACCELERATE_LOG_LEVEL=info accelerate launch --config_file accelerate_configs/deepspeed_zero3.yaml scripts/run_simpo.py training_configs/mistral-7b-instruct-simpo.yaml` using 1 A100-80G.

accelerator.prepare() cuda OOM
![20240529-110755](https://github.com/princeton-nlp/SimPO/assets/92615159/0440c839-3265-44c2-84df-8e20a6b418a0)

I encountered the same problem on 2 A800-80G.

Any ideas how to resolve?
Thanks

**Comment by yumeng5** [comment]
Hi,

The original training scripts were set for 8x80GB GPUs. If you have fewer GPUs you may need to tune down `per_device_train_batch_size` and/or `max_length` and `max_prompt_length`. I tried running the Mistral-Base training script which uses shorter sequence lengths and it worked fine on 2x80GB GPUs with `per_device_train_batch_size=1`. Another way is to apply LoRA/QLoRA training.

I hope this helps.

Best,
Yu

**Comment by zouce** [comment]
Thanks for your reply!
I tried running this code on 4 80G GPUs and solved the problem.

**Comment by smiles724** [comment]
Thanks for your response! PEFT with LoRA is an option that enables large batch sizes and fewer computational resources. However, I wonder whether you have compared the performance between LoRA and full fine-tuning? Will PEFT decrease the performance of SimPO?
