### ISSUE TITLE
Question about the length-normalization

### ISSUE THREAD

**Issue by yujiaw98** [princeton-nlp/SimPO#13]
Hi, thank you for the interesting work. 

I have a question regarding the length-normalization in the “scripts/simpo_trainer.py” file. It appears that the key difference in the concatenated_forward function between simpo_trainer and dpo_trainer is that simpo_trainer uses `average_log_prob`. I assume that setting `average_log_prob=True` averages over `loss_mask.sum(-1)`, contributing to the length-normalization in simpo. Does this interpretation make sense?

Thanks!

**Comment by yumeng5** [comment]
Yes, that's where the length-normalization was implemented.

Thanks,
Yu
