### ISSUE TITLE
Confusing Code logic

### ISSUE THREAD

**Issue by syboomsy** [princeton-nlp/SimPO#15]
![image](https://github.com/princeton-nlp/SimPO/assets/57123221/e4891c96-ecff-4791-befc-e35998daa7a1)
Could anyone explain why the parent class DPOTrainer is initialized twice here in SimpoTrainer's constructor function?

**Comment by yumeng5** [comment]
Hi,

Thanks for catching it! The double call of `super().__init__(**kwargs)` was unintended and was an oversight during the code cleanup. It's been fixed now.

Best,
Yu

**Comment by syboomsy** [comment]
Problem solved.
