### ISSUE TITLE
ValueError: Unknown split "train". Should be one of ['train_iteration_1', 'test_iteration_1', 'train_iteration_2', 'test_iteration_2', 

### ISSUE THREAD

**Issue by qiuwenbogdut** [princeton-nlp/SimPO#18]
The training script I used was:
`HF_ENDPOINT=https://hf-mirror.com ACCELERATE_LOG_LEVEL=info accelerate launch --config_file accelerate_configs/deepspeed_zero3.yaml scripts/run_simpo.py training_configs/mistral-7b-instruct-simpo.yaml`

Then the following bug occurred:
 
  
  ```
File "/opt/conda/envs/simpo/lib/python3.10/site-packages/datasets/load.py", line 2621, in load_dataset
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/opt/conda/envs/simpo/lib/python3.10/site-packages/datasets/arrow_reader.py", line 480, in _rel_to_abs_instr
    **raise ValueError(f'Unknown split "{split}". Should be one of {list(name2len)}.')
ValueError: Unknown split "train". Should be one of ['train_iteration_1', 'test_iteration_1', 'train_iteration_2', 'test_iteration_2', 'train_iteration_3', 'test_iteration_3'].**
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/opt/conda/envs/simpo/lib/python3.10/site-packages/datasets/builder.py", line 1266, in as_dataset
    datasets = map_nested(
```
    

    
<img width="603" alt="image" src="https://github.com/princeton-nlp/SimPO/assets/17745161/20763581-2348-47a6-ab56-959284d06069">

**Comment by yumeng5** [comment]
Hi,

Thanks for reporting the bug. We have fixed the dataset link in `mistral-7b-instruct-simpo.yaml`. Specifically, the updated dataset `princeton-nlp/mistral-instruct-ultrafeedback` is exactly the same as `snorkelai/Snorkel-Mistral-PairRM-DPO-Dataset` except that we combine the three iterations into one entire set.

I hope this helps.

Best,
Yu

**Comment by qiuwenbogdut** [comment]
thanks
