### ISSUE TITLE
For the Instruct setup, why do different models require different training datasets? Can the same dataset be used? 

### ISSUE THREAD

**Issue by qiuwenbogdut** [princeton-nlp/SimPO#19]
<img width="744" alt="image" src="https://github.com/princeton-nlp/SimPO/assets/17745161/d1a45e2e-63da-4bff-a54c-427e991601bf">
<img width="696" alt="image" src="https://github.com/princeton-nlp/SimPO/assets/17745161/87507b44-1a89-4c01-97b4-ab4b0a82f9e0">

For the Instruct setup, why do different models require different training datasets? Can the same dataset be used?

**Comment by yumeng5** [comment]
Hi,

The instruction setups are meant to represent "on-policy" settings where the responses in the preference dataset are generated by the to-be-trained policy model itself. Therefore, the mistral-instruct and llama3-instruct setups use the UltraFeedback prompts but regenerate winning/losing responses with mistral-instruct and llama3-instruct, respectively.

There is nothing wrong with using a different preference training dataset, but it'll change the "on-policy" setting to an "off-policy" setting (similar to the base setups in our paper), and it's expected that the performance of the final model will generally become worse.

Best,
Yu

**Comment by qiuwenbogdut** [comment]
for the base setups ,  whether "on-policy" settings (regenerate winning/losing responses with mistral-base and llama3-base) will get better performance.

**Comment by yumeng5** [comment]
In general on-policy settings will yield better performance, though we haven't tried it under the base setups -- the goal of creating the base setups was to facilitate transparent and direct comparisons with models (e.g., Zephyr) trained using the same off-the-shelf preference datasets (e.g., UltraFeedback).
