### ISSUE TITLE
Unable to reproduce the results of DPO

### ISSUE THREAD

**Issue by AGTSAAA** [princeton-nlp/SimPO#23]
Hi,

Thank you for your work.

Could you please tell me what the hyperparameters for Mistral Base 7B DPO (Zephyr), i.e., the vanilla DPO are?

I utilized beta=0.01 and beta=0.1 but can not reproduce the performance. For instance,

it only achieved 0.45 for TruthfulQA, whereas Mistral Base 7B DPO achieves 0.53.

Thank you very much.

**Comment by yumeng5** [comment]
Hi,

We followed the official Zephyr training script for the DPO experiments:

https://github.com/huggingface/alignment-handbook/blob/main/recipes/zephyr-7b-beta/dpo/config_full.yaml

Best,
Yu

**Comment by niravlg** [comment]
Hi @yumeng5,
Did you use the same hyperparameters for DPO on LLAMA-3-8B SFT?

**Comment by glorgao** [comment]
@niravlg for your information:

Here are results of reruning DPO trainer with `meta-llama/Meta-Llama-3-8B-Instruct`. All other hyperparameters follows the  configurations in `llama-3-8b-instruct-simpo.yaml` except $\beta$, and `trl==0.8.6`.

`\beta=0.005,  LC=40.19,  WR=37.20`
`\beta=0.01,  LC=36.18,  WR=34.29`
`\beta=0.02,  LC=34.70,  WR=33.65`
 
 I used the same hardware (H100 X 8) as described in the paper.

**Comment by RikkiXu** [comment]
Hi @yumeng5, @glorgao Can I ask about the beta and leaning rate of Mistral-7B-Instruct-DPO? I can't reproduce the results in the paper.
