### ISSUE TITLE
TRL version should be 0.8.6

### ISSUE THREAD

**Issue by blakechi** [princeton-nlp/SimPO#25]
Hello,

Thanks for your great work! As TRL released new versions, the arguments, like `ref_model_init_kwargs`, don't match anymore.

I backtracked the time of your release so I think `trl` should be `0.8.6`. Will be great to add a note or `requirements.txt` for new comers.

Best,
Blake

**Comment by yumeng5** [comment]
Hi,

Thanks for your note! Yes, the TRL library is being actively updated, and we noticed that there were several issues and bugs when the TRL library version mismatched what we used in our experiments.

We are working on a PR to add SimPO to TRL and hopefully, that'll resolve most of the issues. We'll update our codebase soon as well. Please stay tuned!

Best,
Yu

**Comment by blakechi** [comment]
close as the new release will fix it
