### ISSUE TITLE
Change of Mistral Chat template

### ISSUE THREAD

**Issue by mianzhang** [princeton-nlp/SimPO#26]
Hi,

I am a little confused as to why you changed the chat template of Mistral when doing training:
https://github.com/princeton-nlp/SimPO/blob/main/scripts/run_simpo.py#L45

Best,
Mian

**Comment by yumeng5** [comment]
Hi,

This is because the original Mistral chat template doesn't support system prompts, and without changing it, the code will error out when processing the UltraFeedback dataset. Check out the details here:
https://github.com/vllm-project/vllm/discussions/2112#discussioncomment-9224099

Best,
Yu

**Comment by mianzhang** [comment]
Thanks~
