### ISSUE TITLE
Question about apply_chat_template to prompt

### ISSUE THREAD

**Issue by EganGu** [princeton-nlp/SimPO#30]
In this repo, I noticed that the input prompt was applied to chat_template. 
https://github.com/princeton-nlp/SimPO/blob/baf9b8428dc1d602de1801a4e19dde295916cea7/scripts/run_simpo.py#L111
However, in your PR to `trl`, it seems that chat_template was not used for the prompt. 
https://github.com/huggingface/trl/blob/223ce737d651a78a9b54ee1a4472fc4e4eb61760/examples/scripts/simpo.py#L95
And I have found this to be common in other examples in `trl`. 
I am not sure what the difference is between these two practices and what the motivation is for each. Could you kindly tell me?

**Comment by xiamengzhou** [comment]
I think both sources of code use apply_chat_template?

**Comment by EganGu** [comment]
Problem solved.
The same issue is in [#1752](https://github.com/huggingface/trl/issues/1752).
