### ISSUE TITLE
simloss has no length normalization in simpo loss

### ISSUE THREAD

**Issue by hjc3613** [princeton-nlp/SimPO#32]
I can not understand the simpo loss in this project, as it has no lengh normalization showed in the paper:
![0DA4804D-526F-476f-9C53-7608263BBE80](https://github.com/princeton-nlp/SimPO/assets/37894838/4cbde10f-cd4a-4cba-841d-4126782ca42e)

**Comment by niravlg** [comment]
I agree, can the authors please clarify where this is implemented?
I don't see it implemented anywhere in the [trainer script](https://github.com/princeton-nlp/SimPO/blob/main/scripts/simpo_trainer.py#L15).

**Comment by yumeng5** [comment]
Hi @niravlg @hjc3613 

The length normalization is implemented here:
https://github.com/princeton-nlp/SimPO/blob/4142d762bca31c92714ba5dd681d3f857a1eae6b/scripts/simpo_trainer.py#L88

Best,
Yu

**Comment by niravlg** [comment]
Thanks! @yumeng5
