### ISSUE TITLE
Lora about simpo.

### ISSUE THREAD

**Issue by hitszxs** [princeton-nlp/SimPO#39]
Have the authors conducted any fine-tuning using the LoRA method on the SimPO approach? If so, what were the results like?

Hope for your reply！

**Comment by xiamengzhou** [comment]
Hi! We haven't tried LoRA on our methods yet. Feel free to experiment with it, and we'd love to hear how it affects SimPO's results!

**Comment by EsYoon7** [comment]
Hi, I'm not author but I tried training simpo with lora dimension 256 from the sft checkpoint uploaded in the github, and I got almost similar mt bench score (w. gpt4) like 7.8 for the llama-3-8b-base

**Comment by hitszxs** [comment]
> Hi, I'm not the author but I tried training simpo with lora dimension 256 from the sft checkpoint uploaded in the github, and I got almost similar mt bench score (w. gpt4) like 7.8 for the llama-3-8b-base

Wow, that is amazing. I think MT-bench has some randomness. I found lora may have higher score too.

**Comment by hitszxs** [comment]
> Hi, I'm not the author but I tried training simpo with lora dimension 256 from the sft checkpoint uploaded in the github, and I got almost similar mt bench score (w. gpt4) like 7.8 for the llama-3-8b-base
Hello, I'd like to know if your score of 7.8 refers to the result of the first round or the combined results of both rounds.

**Comment by EsYoon7** [comment]
It is average of both turns. For the first round, the score was 8.34 and the second round score was 7.43.

**Comment by dhdbsrlw** [comment]
> Hi, I'm not the author but I tried training simpo with lora dimension 256 from the sft checkpoint uploaded in the github, and I got almost similar mt bench score (w. gpt4) like 7.8 for the llama-3-8b-base 

Could you share your training recipe (hyperparams) for Lora training in more detailed way?

**Comment by AIR-hl** [comment]
> > Hi, I'm not the author but I tried training simpo with lora dimension 256 from the sft checkpoint uploaded in the github, and I got almost similar mt bench score (w. gpt4) like 7.8 for the llama-3-8b-base
> 
> Wow, that is amazing. I think MT-bench has some randomness. I found lora may have higher score too.

请问您的实验中Lora也表现出更好的效果是吗？
