### ISSUE TITLE
Hi, could you please provide the exact versions of the packages needed to reproduce the results and your released checkpoint?

### ISSUE THREAD

**Issue by AGTSAAA** [princeton-nlp/SimPO#40]
Hi, 

could you please provide the exact versions of the packages (TRL, Transformer, Handbook, Deepspeed and so on ) needed to reproduce the results and your released checkpoint?

Thank you very much

**Comment by yumeng5** [comment]
Hi,

We have added an environment file for the package versions here: https://github.com/princeton-nlp/SimPO/blob/main/environment.yml

Best,
Yu
