### ISSUE TITLE
Use a better `ultrafeedback`

### ISSUE THREAD

**Issue by AIR-hl** [princeton-nlp/SimPO#43]
I notice that `mistral-orpo-beta` has been trained on `argilla/ultrafeedback-binarized-preferences-cleaned`, but  simpo and other baselines was trained on `HuggingFaceH4/ultrafeedback_binarized`. Did you try to experiment on the first ultrafeedback dataset to make a better performence?

**Comment by yumeng5** [comment]
Hi,

We haven't tried using a different UltraFeedback version, but I think the relative performance comparisons among different methods should generally hold regardless of which version we use. If you are looking to obtain better performance, we'd suggest running the Mistral-Instruct setting which uses on-policy data and yields better results than the original off-policy UltraFeedback.

Best,
Yu
