### ISSUE TITLE
Could you offer the packages' version of alpaca_eval 2 and the generated answers? 

### ISSUE THREAD

**Issue by sunjie279** [princeton-nlp/SimPO#44]
Outstanding work! I followed your generation configuration and template to generate answers using [princeton-nlp/Llama-3-Instruct-8B-SimPO](https://huggingface.co/princeton-nlp/Llama-3-Instruct-8B-SimPO). However, I obtained the same answers with alpaca_eval==0.6.1 and 0.6.2, but different answers with alpaca_eval==0.6.3 (without the do_sample parameter).

I evaluated the answers (AE=0.6.1/0.6.2) twice and got scores of (43.86, 38.37) and (44.67, 39.2), while the answers (AE=0.6.3) received scores of (43.2, 38.42). All these scores are below the scores reported in your paper (44.7, 40.5).

Could you provide the environmental information used when you evaluated the models? Additionally, it would be helpful if you could share the outputs of the models (AE2, Llama-3-Instruct-8B-SimPO).

Thank you very much!

**Comment by yumeng5** [comment]
Hi,

Yes, it looks like the latest alpaca eval package created certain issues for reproducibility. We have mentioned in the README [here](https://github.com/princeton-nlp/SimPO?tab=readme-ov-file#reproducing-alpacaeval-2-numbers) that it's recommended to use `alpaca-eval==0.6.2`.

Thanks,
Yu
