### ISSUE TITLE
Can you share the loss log of `Llama-3-8B-Instruct`

### ISSUE THREAD

**Issue by AIR-hl** [princeton-nlp/SimPO#45]
I recipe the experiment using `trl` on smaller device, so I want to refer to the official training log to determine whether the execution is normal.

**Comment by yumeng5** [comment]
Hi,

Please find the training curves here: https://wandb.ai/yumeng0818/simpo

Best,
Yu

**Comment by Xalp** [comment]
Hi, is it possible that you also share the loss log for llama-3-8b-it v0.2 ?

**Comment by yumeng5** [comment]
@Xalp The logs can be found here:

https://wandb.ai/yumeng0818/simpo/runs/zvv56fcj?nw=nwuseryumeng0818
