### ISSUE TITLE
Could you add licenses to the preference datasets after reward model labeling on huggingface?

### ISSUE THREAD

**Issue by hanyang1999** [princeton-nlp/SimPO#46]
Hi authors,
Thank you for the nice works and release of the datasets. Could you add corresponding licenses to the released datasets, namely https://huggingface.co/datasets/princeton-nlp/llama3-ultrafeedback-armorm and https://huggingface.co/datasets/princeton-nlp/llama3-ultrafeedback? Correspondingly it has no licenses, and it will be greatly helpful to add like MIT license to let us officially use them.

**Comment by yumeng5** [comment]
Thanks! We have added the MIT license. For the dataset creation, we used random seeds 13, 21, 42, 79, and 100 with a temperature of 0.8 for sampling to obtain 5 responses per prompt. I hope this helps!

Best,
Yu

**Comment by hanyang1999** [comment]
Thank you for the prompt replies! Closed the issues!
