### ISSUE TITLE
Cannot install alignment-handbook==0.4.0

### ISSUE THREAD

**Issue by Shentao-YANG** [princeton-nlp/SimPO#48]
Dear authors,

Thank you so much for the dedicated efforts in reproducibility! I was trying to build the environment by using the provided [environment.yml](https://github.com/princeton-nlp/SimPO/blob/main/environment.yml), but nevertheless met the following issue
```
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.10.9; 0.2.0 Requires-Python >=3.10.9
ERROR: Could not find a version that satisfies the requirement alignment-handbook==0.4.0.dev0 (from versions: none)
ERROR: No matching distribution found for alignment-handbook==0.4.0.dev0
```
It seems to me that the [latest version of alignment-handbook](https://pypi.org/project/alignment-handbook/) on pip is 0.2.0, which cause the above error message. 

Would you mind letting me know how I may revolve this version issue in building the environment? Or otherwise which version of `alignment-handbook` (and possibly other packages as well) should I use?

**Comment by yumeng5** [comment]
Hi @Shentao-YANG 

We recommend following the official installation instructions in [alignment-handbook](https://github.com/huggingface/alignment-handbook?tab=readme-ov-file#installation-instructions) (i.e., build from source):

```
git clone https://github.com/huggingface/alignment-handbook.git
cd ./alignment-handbook/
python -m pip install .
```
which will install `alignment-handbook==0.4.0.dev0`.

Best,
Yu
