### ISSUE TITLE
How to run the evaluation on GPT-4 Turbo

### ISSUE THREAD

**Issue by Xalp** [princeton-nlp/SimPO#49]
Hi, you mentioned in your paper that: For MT-Bench, we report the average MT-Bench score with GPT-4 and GPT-4-Preview-1106 as the judge model. Is the results of GPT-4-Preview-1106 reported under the GPT-4 Turbo column?

**Comment by AIR-hl** [comment]
> Hi, you mentioned in your paper that: For MT-Bench, we report the average MT-Bench score with GPT-4 and GPT-4-Preview-1106 as the judge model. Is the results of GPT-4-Preview-1106 reported under the GPT-4 Turbo column?

Hello! I have the same question about gpt-4-turbo, have you solved this problem?

**Comment by Xalp** [comment]
hi, the GPT-4-Preview-1106 is GPT-4 Turbo...
