### ISSUE TITLE
Question about RRHF

### ISSUE THREAD

**Issue by SihengLi99** [princeton-nlp/SimPO#5]
Hi,

Very insightful work!
While I have some question about the relation between RRHF[1] and SimPO.
Could you please give a brief introduction?

Thanks!

[1] RRHF: Rank responses to align language models with human feedback. In NeurIPS, 2023.

**Comment by yumeng5** [comment]
Hi,

Thanks for the question. SimPO and RRHF both use average log-likelihood as the reward. The main differences are:
- RRHF has an SFT loss whereas SimPO doesn't
- RRHF uses a hinge-like ranking loss (without a margin) whereas SimPO uses the Bradley-Terry ranking loss with a margin

We tested RRHF (with and without the SFT loss) under the Mistral-Base setup and tuned the learning rates in [5e-7, 1e-6, 5e-6, 1e-5]. The best performance of RRHF measured by AlpacaEval 2 length-controlled win rate (LC) and raw win rate (WR) are as follows:
| Method   | LC (%) | WR (%) |
| -------- | ------- | ------- |
| DPO  | 15.1 | 12.5 |
| SimPO  | 21.5 | 20.8 |
| RRHF | 11.6 | 10.2 |
| RRHF w/o SFT | degenerate | degenerate |

where RRHF w/o SFT always generates repetitive patterns without following instructions regardless of the learning rates.

Given these observations, we believe that the Bradley-Terry ranking loss is essential when using average log-likelihood as the reward formulation. It is also possible that hinge-like ranking losses could work with thorough tuning of the margin, and we leave that for future studies.

I hope this helps!

Best,
Yu

**Comment by SihengLi99** [comment]
Hi,

Thanks for your answer. It is very insightful for me!

Best regards,
Siheng

Yu Meng ***@***.***> 于2024年5月29日周三 05:06写道：
