### ISSUE TITLE
Model Request:  Meta-Llama-3.1-8B-Instruct 

### ISSUE THREAD

**Issue by Bearsaerker** [princeton-nlp/SimPO#52]
I love your SimPo finetune of Gemma 9b. Unfortunately I'm very GPU poor but I'd love to see that on the Llama-3.1. Is there any chance we would get this model? Thank you for your great work!

**Comment by xiamengzhou** [comment]
Hi thanks for your interest! We are still testing the Llama-3.1 models, keep tuned!
