### ISSUE TITLE
No template of gemma2 when evaluating it on AE2

### ISSUE THREAD

**Issue by sunjie279** [princeton-nlp/SimPO#53]
The SimPO is great! 
When I evaluated gemma2 on AE2, I did not find the template of gemma2. Could you update the template of gemma2?

**Comment by xiamengzhou** [comment]
Hi thank you!
The template is under the DPO model's folder: https://github.com/tatsu-lab/alpaca_eval/blob/main/src/alpaca_eval/models_configs/gemma-2-9b-it-DPO/prompt.txt
