### ISSUE TITLE
What version of Mistral 7B was used for princeton-nlp/Mistral-7B-Instruct-SimPO ?

### ISSUE THREAD

**Issue by junkangwu** [princeton-nlp/SimPO#56]
I have noticed some differences in the tokenizer.json files between the current versions of mistralai/Mistral-7B-Instruct-v0.2 and princeton-nlp/Mistral-7B-Instruct-SimPO. Here are some related links for further reference:

- Align tokenizer with mistral-common ([#141](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/discussions/141))

- https://github.com/princeton-nlp/SimPO/issues/38#issuecomment-2228497875

@xiamengzhou @yumeng5

**Comment by xiamengzhou** [comment]
I think we are sure that the released models have the correct but old tokenizer (as in that the training tokenizer and the one we uploaded to HF are consistent), which is different from the up-to-date version!
