### ISSUE TITLE
Evaluate about  arena-hard.

### ISSUE THREAD

**Issue by hitszxs** [princeton-nlp/SimPO#57]
Hello, do you know why i evaluate your checkpoint by arena-hard-auto, it will have '<|eot_id|>' in the end of answer? I have used your config:
bench_name: arena-hard-v0.1
temperature: 0.0
max_tokens: 4096
num_choices: 1
stop_token_ids:
- 128001
- 128009
model_list:
- Llama-3-Base-8B-SFT-SimPO

**Comment by hitszxs** [comment]
I try to add a postprocess on output to solve it.

**Comment by xiamengzhou** [comment]
Hi @hitszxs my experience is that you would have to edit the arena-hard code to make it accept stop_token_ids.

**Comment by hitszxs** [comment]
> Hi @hitszxs my experience is that you would have to edit the arena-hard code to make it accept stop_token_ids.

Thanks for your reply! I tried it and it works.
