### ISSUE TITLE
Questions about SimPO parameters for gemma-2-9b model

### ISSUE THREAD

**Issue by junkangwu** [princeton-nlp/SimPO#65]
Hi @yumeng5 @xiamengzhou ,
 
I hope this email finds you well. I'm currently working on reproducing the SimPO results with the gemma-2-9b model and have encountered some issues. I would greatly appreciate your guidance on the following points:
 
Regarding the num_processes parameter, should it be set to 4 or 8 for gemma-2-9b? I noticed that other models (llama3-8b, mistral-7b) use 4, but setting it to 4 for gemma-2-9b results in out-of-memory errors.
 
Could you please advise on the appropriate settings for the following parameters:
 
gradient_accumulation_steps
per_device_train_batch_size
per_device_eval_batch_size
Are there any other specific considerations or parameter settings I should be aware of when reproducing the results with gemma-2-9b?
 
Your insights would be invaluable in ensuring accurate reproduction of the SimPO results. Thank you in advance for your time and assistance.
 
Best regards,

**Comment by yumeng5** [comment]
Hi @junkangwu 

The `num_processes` parameter refers to how many GPUs you have. In our experiments, we always used 8 H100 GPUs (80GB). During code release, we realized that 8 GPUs may not be available to many users, so we changed the `num_processes` to 4 and the SimPO training scripts have been tested to run successfully on 4 GPUs with 80GB memory. 

For DPO, as you pointed out, the reference model will take more GPU memory, so you might have to adjust `per_device_train_batch_size` to make sure the training can fit your available number of GPUs. And yes, as long as you adjust the `gradient_accumulation_steps` accordingly to make sure the total batch size is 128, you should get similar results.

Best,
Yu
