### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by XYaoooo** [princeton-nlp/SimPO#66]
Hi, could i know your hyper parameters when training with DPO:
batch size, beta, learning rate
I train on 8 A100  with batch size per device = 16  (as you said in the paper, bz=128), it is out of memory. 
Best

**Comment by xiamengzhou** [comment]
Hi you should use gradient accumulation to reduce the effective training batch size. Please refer to this script for more details: https://github.com/princeton-nlp/SimPO/blob/main/training_configs/gemma-2-9b-it-simpo.yaml

**Comment by XYaoooo** [comment]
Got it. Thanks for your advice.
